
SDL_DestroyTexture(tex_blank);
SDL_DestroyTexture(tex_ctrl);
SDL_DestroyTexture(tex_shift);
SDL_DestroyTexture(tex_super);
SDL_DestroyTexture(tex_alt);
SDL_DestroyTexture(tex_general);
SDL_DestroyTexture(tex_generalP);
SDL_DestroyTexture(tex_mouse);
SDL_DestroyTexture(tex_mouse_rightP);
SDL_DestroyTexture(tex_mouse_leftP);
SDL_DestroyTexture(tex_mouse_wheelP);
SDL_DestroyTexture(tex_mouse_wheelup);
SDL_DestroyTexture(tex_mouse_wheeldown);

tex_blank = NULL;
tex_ctrl = NULL;
tex_shift = NULL;
tex_super = NULL;
tex_alt = NULL;
tex_general = NULL;
tex_generalP = NULL;
tex_mouse = NULL;
tex_mouse_rightP = NULL;
tex_mouse_leftP = NULL;
tex_mouse_wheelP = NULL;
tex_mouse_wheelup = NULL;
tex_mouse_wheeldown = NULL;

SDL_DestroyTexture(tex_A);
SDL_DestroyTexture(tex_B);
SDL_DestroyTexture(tex_C);
SDL_DestroyTexture(tex_D);
SDL_DestroyTexture(tex_E);
SDL_DestroyTexture(tex_F);
SDL_DestroyTexture(tex_G);
SDL_DestroyTexture(tex_H);
SDL_DestroyTexture(tex_I);
SDL_DestroyTexture(tex_J);
SDL_DestroyTexture(tex_K);
SDL_DestroyTexture(tex_L);
SDL_DestroyTexture(tex_M);
SDL_DestroyTexture(tex_N);
SDL_DestroyTexture(tex_O);
SDL_DestroyTexture(tex_P);
SDL_DestroyTexture(tex_Q);
SDL_DestroyTexture(tex_R);
SDL_DestroyTexture(tex_S);
SDL_DestroyTexture(tex_T);
SDL_DestroyTexture(tex_U);
SDL_DestroyTexture(tex_V);
SDL_DestroyTexture(tex_W);
SDL_DestroyTexture(tex_X);
SDL_DestroyTexture(tex_Y);
SDL_DestroyTexture(tex_Z);
SDL_DestroyTexture(tex_0);
SDL_DestroyTexture(tex_1);
SDL_DestroyTexture(tex_2);
SDL_DestroyTexture(tex_3);
SDL_DestroyTexture(tex_4);
SDL_DestroyTexture(tex_5);
SDL_DestroyTexture(tex_6);
SDL_DestroyTexture(tex_7);
SDL_DestroyTexture(tex_8);
SDL_DestroyTexture(tex_9);
SDL_DestroyTexture(tex_APOSTROPHE);
SDL_DestroyTexture(tex_BACKSLASH);
SDL_DestroyTexture(tex_BACKSPACE);
SDL_DestroyTexture(tex_COMMA);
SDL_DestroyTexture(tex_DELETE);
SDL_DestroyTexture(tex_DOT);
SDL_DestroyTexture(tex_ENTER);
SDL_DestroyTexture(tex_EQUAL);
SDL_DestroyTexture(tex_ESC);
SDL_DestroyTexture(tex_GRAVE);
SDL_DestroyTexture(tex_LEFTBRACE);
SDL_DestroyTexture(tex_RIGHTBRACE);
SDL_DestroyTexture(tex_SEMICOLON);
SDL_DestroyTexture(tex_SLASH);
SDL_DestroyTexture(tex_SPACE);
SDL_DestroyTexture(tex_TAB);

tex_A = NULL;
tex_B = NULL;
tex_C = NULL;
tex_D = NULL;
tex_E = NULL;
tex_F = NULL;
tex_G = NULL;
tex_H = NULL;
tex_I = NULL;
tex_J = NULL;
tex_K = NULL;
tex_L = NULL;
tex_M = NULL;
tex_N = NULL;
tex_O = NULL;
tex_P = NULL;
tex_Q = NULL;
tex_R = NULL;
tex_S = NULL;
tex_T = NULL;
tex_U = NULL;
tex_V = NULL;
tex_W = NULL;
tex_X = NULL;
tex_Y = NULL;
tex_Z = NULL;
tex_0 = NULL;
tex_1 = NULL;
tex_2 = NULL;
tex_3 = NULL;
tex_4 = NULL;
tex_5 = NULL;
tex_6 = NULL;
tex_7 = NULL;
tex_8 = NULL;
tex_9 = NULL;
tex_APOSTROPHE = NULL;
tex_BACKSLASH = NULL;
tex_BACKSPACE = NULL;
tex_COMMA = NULL;
tex_DELETE = NULL;
tex_DOT = NULL;
tex_ENTER = NULL;
tex_EQUAL = NULL;
tex_ESC = NULL;
tex_GRAVE = NULL;
tex_LEFTBRACE = NULL;
tex_RIGHTBRACE = NULL;
tex_SEMICOLON = NULL;
tex_SLASH = NULL;
tex_SPACE = NULL;
tex_TAB = NULL;



SDL_DestroyRenderer(renderer);
SDL_DestroyWindow(window);
renderer = NULL;
window = NULL;

SDL_Quit();
exit(0);
