
SDL_DestroyTexture(tex_ctrl);
SDL_DestroyTexture(tex_shift);
SDL_DestroyTexture(tex_super);
SDL_DestroyTexture(tex_alt);
SDL_DestroyTexture(tex_general);
SDL_DestroyTexture(tex_mouse);
SDL_DestroyTexture(tex_mouse_rightP);
SDL_DestroyTexture(tex_mouse_leftP);
SDL_DestroyTexture(tex_mouse_wheelP);
SDL_DestroyTexture(tex_mouse_wheelup);
SDL_DestroyTexture(tex_mouse_wheeldown);

SDL_DestroyTexture(tex_A);
SDL_DestroyTexture(tex_B);
SDL_DestroyTexture(tex_C);
SDL_DestroyTexture(tex_D);
SDL_DestroyTexture(tex_E);
SDL_DestroyTexture(tex_F);
SDL_DestroyTexture(tex_G);
SDL_DestroyTexture(tex_H);
SDL_DestroyTexture(tex_I);
SDL_DestroyTexture(tex_J);
SDL_DestroyTexture(tex_K);
SDL_DestroyTexture(tex_L);
SDL_DestroyTexture(tex_M);
SDL_DestroyTexture(tex_N);
SDL_DestroyTexture(tex_O);
SDL_DestroyTexture(tex_P);
SDL_DestroyTexture(tex_Q);
SDL_DestroyTexture(tex_R);
SDL_DestroyTexture(tex_S);
SDL_DestroyTexture(tex_T);
SDL_DestroyTexture(tex_U);
SDL_DestroyTexture(tex_V);
SDL_DestroyTexture(tex_W);
SDL_DestroyTexture(tex_X);
SDL_DestroyTexture(tex_Y);
SDL_DestroyTexture(tex_Z);
SDL_DestroyTexture(tex_0);
SDL_DestroyTexture(tex_1);
SDL_DestroyTexture(tex_2);
SDL_DestroyTexture(tex_3);
SDL_DestroyTexture(tex_4);
SDL_DestroyTexture(tex_5);
SDL_DestroyTexture(tex_6);
SDL_DestroyTexture(tex_7);
SDL_DestroyTexture(tex_8);
SDL_DestroyTexture(tex_9);
SDL_DestroyTexture(tex_APOSTROPHE);
SDL_DestroyTexture(tex_BACKSLASH);
SDL_DestroyTexture(tex_BACKSPACE);
SDL_DestroyTexture(tex_COMMA);
SDL_DestroyTexture(tex_DELETE);
SDL_DestroyTexture(tex_DOT);
SDL_DestroyTexture(tex_ENTER);
SDL_DestroyTexture(tex_EQUAL);
SDL_DestroyTexture(tex_ESC);
SDL_DestroyTexture(tex_GRAVE);
SDL_DestroyTexture(tex_LEFTBRACE);
SDL_DestroyTexture(tex_RIGHTBRACE);
SDL_DestroyTexture(tex_SEMICOLON);
SDL_DestroyTexture(tex_SLASH);
SDL_DestroyTexture(tex_SPACE);
SDL_DestroyTexture(tex_TAB);


SDL_RenderPresent(renderer);
SDL_DestroyWindow(window);

SDL_Quit();
cout << "closed normally" << endl;
return 0;
